// <auto-generated />
namespace DreamTeam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertBaseData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertBaseData));
        
        string IMigrationMetadata.Id
        {
            get { return "202107111600272_InsertBaseData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
